### PR TITLE
Fixing The OpenCL Headers Path And Temporarily Disabling Support For OpenCL 2.2 Conformance Tests

### PR DESCRIPTION
**Pull request by abhayrjoshi**
The OpenCL headers from https://github.com/KhronosGroup/OpenCL-Headers is currently organised with the folder CL containing the required headers. Hence, the path in the script might not correspond to a valid path.

From the OpenCL-CTS repository (https://github.com/KhronosGroup/OpenCL-CTS), the tag cl22_trunk doesn't exist. Hence, it is better that the tests are disabled for now and can be enabled at a later point in time.

### CODE REVIEW

**Comment by kpet** [comment]
The cl22_trunk branch has been renamed to master. This PR should probably follow the rename instead of commenting out the logic for cl22_trunk. That being said, I'm not very familiar with this framework.

**Comment by InBetweenNames** [comment]
Sorry for the delay -- yes, it should refer to `master` and not `cl22_trunk`, is it possible to amend this?

**Comment by abhayrjoshi** [comment]
Yes, changed the branch for OpenCL 2.2 tests to master.

**Comment by InBetweenNames** [comment]
Thank you!

**Pull request merged**
